import esbuild from "esbuild";
import { build } from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Pre-bundle the federation sidecar with Bun (all deps vendored into one file)
// so a release install never runs `bun install` on the user's machine — that
// install step is the root of the field failures (interrupted installs leave
// partial node_modules; some networks can't complete it at all). Must be
// `bun build --target=bun`: an esbuild node-platform bundle pulls in undici,
// which crashes under Bun (util.markAsUncloneable). Fail-soft: without bun on
// the build machine the define is empty and the plugin falls back to the
// legacy source + install path.
let sidecarBundle = "";
try {
  const out = resolve(__dirname, ".sidecar-bundle.tmp.js");
  execSync(
    `bun build "${resolve(__dirname, "sidecar/federation-sidecar.ts")}" --target=bun --minify --outfile="${out}"`,
    { stdio: "pipe" }
  );
  sidecarBundle = readFileSync(out, "utf8");
  fs.unlinkSync(out);
  console.log(`[build] sidecar bundle embedded (${(sidecarBundle.length / 1024).toFixed(0)} KB, deps vendored — no user-side bun install)`);
} catch (e) {
  console.warn("[build] WARNING: bun unavailable — sidecar bundle not embedded; source + install fallback will be used:", e?.message ?? e);
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  define: {
    __SIDECAR_SOURCE__: JSON.stringify(
      readFileSync(resolve(__dirname, 'sidecar/federation-sidecar.ts'), 'utf8')
    ),
    __SIDECAR_PACKAGE_JSON__: JSON.stringify(
      readFileSync(resolve(__dirname, 'sidecar/package.json'), 'utf8')
    ),
    __SIDECAR_BUNDLE__: JSON.stringify(sidecarBundle),
  },
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  // Obsidian reads manifest.json's version — sync it from package.json so every
  // production build ships the real version (drift breaks human update verification).
  const pkgVersion = JSON.parse(fs.readFileSync(new URL("./package.json", import.meta.url), "utf8")).version;
  const manifestUrl = new URL("./manifest.json", import.meta.url);
  const manifest = JSON.parse(fs.readFileSync(manifestUrl, "utf8"));
  if (manifest.version !== pkgVersion) {
    manifest.version = pkgVersion;
    fs.writeFileSync(manifestUrl, JSON.stringify(manifest, null, "\t") + "\n");
  }
  await context.rebuild();

  // Post-build smoke check: ensure no unreplaced build sentinels remain
  let bundle;
  try {
    bundle = fs.readFileSync(new URL("./main.js", import.meta.url), "utf8");
  } catch {
    console.error("[post-build] Could not read main.js for sentinel check");
    process.exit(1);
  }
  const sentinelPattern = /__[A-Z0-9_]+__/g;
  const matches = bundle.match(sentinelPattern);
  if (matches && matches.length > 0) {
    const unique = [...new Set(matches)];
    console.error(
      "[post-build] ERROR: unreplaced build sentinels found in main.js: " +
        unique.join(", ")
    );
    process.exit(1);
  }
  console.log("[post-build] sentinel check passed — no unreplaced build constants.");

  process.exit(0);
} else {
  await context.watch();
}
